---
clean_deploy_title: devnet13

block_gas_limit: 50_000_000
block_time: 5

polycli_tag: 0.1.22
edge_tag: v0.9.0
geth_tag: v1.11.6
go_tag: 1.19.9.linux-amd64

# this is the amount of value that will be transfered on the rootchain to the deployer address and the validators
# rootchain_validator_fund_amount: 100ether
# rootchain_deployer_fund_amount: 10000000ether
rootchain_deployer_fund_amount: 10ether
rootchain_validator_fund_amount: 1ether



# this is the rpc url that will be used for the root chain
# rootchain_json_rpc: http://geth-001:8545
rootchain_json_rpc: https://matic-mumbai.chainstacklabs.com

# When our l1 is geth with an unlocked account, we'll need to send
# ether from the randomly created coinbase to our predetermined
# account. Set this to true in order to fund. Set this to false if the
# coinbase account is already funded

# fund_rootchain_coinbase: true
fund_rootchain_coinbase: false

# This account is just for testing purposes. Don't actually use it. If
# the L1 is NOT an unlocked test account, then you'll need some wallet
# for funding validators. The address and private key here are used for this purpose
rootchain_coinbase_address: "0xC7FDEe289150041f2c4AAEF095e8a6715223663C"
rootchain_coinbase_private_key: "0xc0ffec0ffec0ffec0ffec0ffec0ffec0ffec0ffec0ffec0ffec0ffec0ffeDEAD"

ansible_ssh_private_key_file: ~/devnet_private.key
ansible_ssh_common_args: >
  -o IdentitiesOnly=yes
  -o StrictHostKeyChecking=no
  -o ProxyCommand="sh -c \"aws ssm start-session --target %h --document-name AWS-StartSSHSession --parameters 'portNumber=%p'\""
ansible_user: ubuntu
ansible_become: true
ansible_ssh_retries: 5
