---
- name: Create a primary partition on "{{ storage_device_location }}"
  community.general.parted:
    device: "{{ storage_device_location }}"
    number: 1
    label: gpt
    part_start: 0%
    part_end: 100%
    part_type: primary
    fs_type: ext4
    name: "{{ storage_partition_name }}"
    unit: "%"
    state: present

- name: Ext4 Format {{ storage_device_location }}
  community.general.filesystem:
    dev: "{{ storage_device_location }}p1"
    fstype: ext4

- name: Refresh metadata
  ansible.builtin.setup: {}

- name: Create mountpoint
  ansible.builtin.file:
    path: "{{ storage_mount_point }}"
    state: directory
    mode: 0750

- name: Mount {{ storage_device_location }}
  ansible.posix.mount:
    path: "{{ storage_mount_point }}"
    src: "UUID={{ ansible_devices[storage_device_name]['partitions'][storage_device_name + 'p1']['uuid'] }}"
    fstype: ext4
    state: mounted
